version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DEFAULT_REGION=sa-east-1
    volumes:
      - ./entrypoint.sh:/docker-entrypoint-initaws.d/entrypoint.sh
    networks:
      - localstack_network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - localstack_network

networks:
  localstack_network:
    driver: bridge